src/studybudy/notes/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from . import views

app_name = 'notes'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^upload_notes/$', views.upload_notes, name='upload_notes'),
    url(r'^new_folder/$', views.create_newFolder, name='create_new_folder'),
    url(r'^new_file/$', views.create_newFile, name='create_new_file'),
    url(r'^rename_file/$', views.rename_File, name='rename_file'),
    url(r'^details/$', views.get_details, name='details'),
    url(r'^change_description/$', views.change_description, name='change_description'),
    url(r'^make_public/$', views.make_public, name='ajax_change_public'),
    url(r'^star_file/$', views.star_file, name='star_file'),
    url(r'^share_file/$', views.share_file, name='ajax_share_file'),
    url(r'^open_file/$', views.open_file, name='open_file'),
    url(r'^(?P<file_id>[0-9]+)/open_File/$', views.open_File, name='open_file_new_tab'),
    url(r'^save_file/$', views.save_file, name='save_file'),
    url(r'^delete_file/$', views.delete_file, name='delete_file'),
    url(r'^quiz_note/$', views.quiz_note, name='quiz_note'),
    url(r'^summarize/$', views.summarize, name='summarize'),
    url(r'^quiz_result/$', views.quiz_result, name='quiz_result'),
    url(r'^move_list/$', views.move_list, name='move_list'),
    url(r'^move/$', views.move, name='move'),
    url(r'^(?P<file_id>[0-9]+)/download_file/$', views.download_file, name='download_file'),
    url(r'^filter_note/$', views.filter_note, name='filter_note'),
    url(r'^(?P<order_id>[a-z]+)/order_note/$', views.order_note, name='order_note'),
    # re_path(r'^order_note/(?P<order>[a-z]{4})/(?P<file_type>[a-z]{2})/$', views.order_note, name='order_note'),
    url(r'^(?P<view_id>[a-z]+)/change_view/$', views.change_view, name='change_view'),
    url(r'^stared_note/$', views.stared, name='stared_note'),
    url(r'^shared_note/$', views.shared, name='shared_note'),
    url(r'^(?P<folder_id>[0-9]+)/folder_content/$', views.folder_content, name='folder_content'),
]

src/studybudy/quiz/urls.py
from django.conf.urls import url
from . import views

app_name = 'quiz'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^save_quiz/$', views.save_quiz, name='save_quiz'),
    url(r'^(?P<file_id>[0-9]+)/quiz_attempt/$', views.quiz_attempt, name='quiz_attempt'),
]

src/studybudy/reminder/urls.py
from django.conf.urls import url
from . import views

app_name = 'reminder'

urlpatterns = [
    url(r'^$', views.task_list, name='task_list'),
    url(r'^add_task/$', views.add_task, name='add_task'),
    url(r'^(?P<task_id>[0-9]+)/edit_task/$', views.edit_task, name='edit_task'),
    url(r'^delete_task/$', views.delete_task, name='delete_task'),
    url(r'^complete_task/$', views.complete_task, name='complete_task'),
    # url(r'^add_task/$', AppointmentCreateView.as_view(), name='add_task'),

]

src/studybudy/studybudy/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from .views import login_page, register_page, login_user, register_user, logout_user
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
 
 


app_name = 'studybudy'





urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', login_page, name='login_page'),
    url(r'^login_user/$', login_user, name='login_user'),
    url(r'^Register/$', register_page, name='register_page'),
    url(r'^register_user/$', register_user, name='register_user'),
    url(r'^logout/$', logout_user, name='logout_user'),
    url(r'^Dashboard/', include('notes.urls')),
    url(r'^Trash/', include('trash.urls')),
    url(r'^Quiz/', include('quiz.urls')),
    url(r'^User/', include('users.urls')), 
    url(r'^Reminder/', include('reminder.urls'))  
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/studybudy/reminder/models.py
import random, os
from django.db import models
from users.models import User
# from django.utils.six import python_2_unicode_compatible
from timezone_field import TimeZoneField




# Create your models here.
# @python_2_unicode_compatible
class TaskReminder(models.Model):
    user                = models.ForeignKey(User, related_name="task_creator", on_delete=models.CASCADE, blank=True, null=True,)
    phone_number        = models.CharField(max_length=15)
    task                = models.CharField(max_length=150)
    time                = models.DateTimeField(blank=True, null=True)
    time_zone           = TimeZoneField(default='UTC')
    task_id             = models.CharField(max_length=50, blank=True, editable=False)
    created             = models.DateTimeField(auto_now_add=True)
    completed           = models.BooleanField(default=False)
    passed              = models.BooleanField(default=False)

    def __str__(self):
        return 'Reminder {0} - {1}'.format(self.pk, self.user.last_name)

src/studybudy/reminder/forms.py
import json, os
from django import forms
from .models import TaskReminder
from datetime import datetime


# from .models import User

class DateInput(forms.DateInput):
    input_type = "date"

class TimeInput(forms.TimeInput):
    input_type = "time"

class TaskForm(forms.Form):

    task = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "col": 4,
                "placeholder" : "Enter Task",
                "class" : "form-control", 
                "id" : "task",
            }
        )
    )

    date_scheduled = forms.DateField(
        widget=DateInput(
            format="%Y-%m-%d",
                attrs={
                "col" : 4,
                "class": "form-control",
                "id" : "date_scheduled",
                "placeholder" : "dd/mm/yyy"
            }
        )
    )

    time = forms.TimeField(
        widget=TimeInput(
            format="%H:%M:%S",
                attrs={
                "col" : 4,
                "class": "form-control",
                "id" : "time",
            }
        )
    )



    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        instance    = getattr(self, 'instance', None)
        # if instance and instance.pk:
        #     print("here")
        #     self.fields['date_scheduled'].required = False

        #     if instance is not None:
        #         self.fields["task"].initial             = instance.task
        #         self.fields["date_scheduled"].initial   = instance.time.strftime('%Y-%m-%d')

    def clean_date_scheduled(self):
        expiry_date = self.cleaned_data.get('date_scheduled')
        now         = datetime.today().strftime('%Y-%m-%d')
        format_exp  = datetime.strptime(str(expiry_date), "%Y-%m-%d").date()
        format_now  = datetime.strptime(str(now), "%Y-%m-%d").date()
        if format_now > format_exp:
             raise forms.ValidationError("Cannot set a past Date")
        else:
            return expiry_date

    def clean(self):
        data = self.cleaned_data
        print(data)
        return data

src/studybudy/reminder/views.py
import os, json, time, pytz
from datetime import datetime
from django.shortcuts import render
from django.conf import settings
from django.contrib.auth import get_user_model
from notes.utils.determine_state import DetermineState
from django.http import HttpResponse, Http404, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.core.files import File
from users.models import UserState
from notes.models import FileSystem
from quiz.models import QuizFileSystem
from .models import TaskReminder
from .forms import TaskForm
from .tasks import send_email_reminder
from django.utils.timezone import make_aware
from users.models import Notifications
from studybudy.settings import BASE_DIR




media_root  = settings.MEDIA_ROOT
Users       = get_user_model()
utc         = pytz.UTC


# Create your views here.
@login_required(login_url='/login')
def task_list(request):
    sname = None
    if (request.user.is_authenticated):
        sname           = request.user.get_short_name()
        state           = UserState.objects.filter(user=request.user).first()
        DS              = DetermineState(state)
        fryp, fry       = DS.determine_order()
        filt, folt      = DS.determine_tab_filter()
        mode            = DS.determine_mode()
        task_list       = TaskReminder.objects.filter(passed=False, user=request.user.id).order_by('created')
        for x in task_list:
            if utc.localize(datetime.now()) > x.time:
                notyss  = Notifications.objects.filter(task_id=x.id).first()
                if notyss is not None:
                    notyss.delete()
                x.delete()

        path            = "reminder/" + mode + "/taskList.html"

        context = {
            'short_name': sname,
            'task_list' : task_list,
        }
    else:
        return redirect("/login")

    return render(request, path, context)


@login_required(login_url='/login')
def add_task(request):
    sname = None
    if (request.user.is_authenticated):
        sname           = request.user.get_short_name()
        form            = TaskForm(request.POST or None)

        if request.method == "POST": 
            form = TaskForm(request.POST)
            if form.is_valid(): 
                task                = form.cleaned_data.get("task").capitalize()
                date_scheduled      = form.cleaned_data.get("date_scheduled")
                time                = form.cleaned_data.get("time")
                timezone            = time.tzname
                data_S              = date_scheduled.strftime('%Y-%m-%d')
                time_S              = time.strftime('%H:%M:%S')
                join_datetime       = data_S + " " + time_S
                date_set            = datetime.strptime(join_datetime, "%Y-%m-%d %H:%M:%S")

                new_task                = TaskReminder()
                new_task.user           = request.user
                new_task.phone_number   = request.user.telephone
                new_task.task           = task
                new_task.time           = make_aware(date_set)
                new_task.save()

                

                if new_task is not None:
                    # send_email_reminder.apply_async(args=(new_task.id,"davidmatthew708@gmail.com"), eta=new_task.time)
                    new_note                = Notifications()
                    new_note.usey           = request.user
                    new_note.task_id        = new_task.id
                    new_note.notify         = task + " reminder has been created"
                    new_note.save()
                    
                return redirect('/Reminder/')

        context = {
            'short_name'    : sname,
            'user'          : request.user,
            'form'          : form,
        }
    else:
        return redirect("/login")

    return render(request, "reminder/Light-mode/addTask.html", context)


@login_required(login_url='/login')
def edit_task(request, task_id):
    sname = None
    if (request.user.is_authenticated):
        sname           = request.user.get_short_name()
        task_inst       = get_object_or_404(TaskReminder, pk=task_id)
        form            = TaskForm(request.POST or None)
        text_task       = task_inst.task
        date_scheduled  = task_inst.time.strftime('%Y-%m-%d')
        time            = task_inst.time.strftime('%H:%M:%S')


        if request.method == "POST": 
            form = TaskForm(request.POST)
            
            if form.is_valid():
                task                = form.cleaned_data.get("task").capitalize()
                date_scheduled      = form.cleaned_data.get("date_scheduled")
                time                = form.cleaned_data.get("time")
                timezone            = time.tzname
                data_S              = date_scheduled.strftime('%Y-%m-%d')
                time_S              = time.strftime('%H:%M:%S')
                join_datetime       = data_S + " " + time_S
                date_set            = datetime.strptime(join_datetime, "%Y-%m-%d %H:%M:%S")

                task_inst.user           = request.user
                task_inst.phone_number   = request.user.telephone
                task_inst.task           = task
                task_inst.time           = make_aware(date_set)
                task_inst.save()
                
                if task_inst is not None:
                    # send_email_reminder.apply_async(args=(new_task.id,"davidmatthew708@gmail.com"), eta=new_task.time)
                    new_note                = Notifications.objects.filter(task_id=task_inst.id).first()
                    new_note.usey           = request.user
                    new_note.task_id        = task_inst.id
                    new_note.notify         = task_inst.task + " reminder has been created"
                    new_note.save()
                
               

                return redirect('/Reminder/')

        context = {
            'short_name'    : sname,
            'user'          : request.user,
            'form'          : form,
            'task'          : text_task,
            'date_scheduled': date_scheduled,
            'time'          : time,
        }
    else:
        return redirect("/login")

    return render(request, "reminder/Light-mode/addTask.html", context)


@login_required(login_url='/login')
def delete_task(request):
    data = {}
    task_id   = request.GET.get('ID')

    if (request.user.is_authenticated):
        active_task = TaskReminder.objects.get(pk=int(task_id))

        if active_task is None:
            data['error'] = "Sorry something went wrong during handlling of operation"
            return JsonResponse(data)

        else:
            active_task.delete()
            noty = Notifications.objects.filter(task_id=int(task_id)).first()
            noty.delete()
            data["success"] = "Task successfully deleted"

    else:
        return redirect("/login")
        

    return JsonResponse(data)

            
@login_required(login_url='/login')
def complete_task(request):
    data = {}
    task_id         = request.GET.get('ID')
    task_status     = request.GET.get('status')

    if (request.user.is_authenticated):
        active_task = TaskReminder.objects.get(pk=int(task_id))

        if active_task is None:
            data['error'] = "Sorry something went wrong during handlling of operation"
            return JsonResponse(data)

        else:
            if task_status == "True":
                active_task.completed = True
            else:
                active_task.completed = False
            active_task.save()
            noty = Notifications.objects.filter(task_id=int(task_id)).first()
            noty.delete()
            data["success"] = "Task has successfully been completed"

    else:
        return redirect("/login")
        

    return JsonResponse(data)

                    
               

          

src/studybudy/templates/reminder/Light-mode/addTask.html
{% extends "base/reminder_base.html" %}
{% load static %}
{%  block content %}

        <main>
            {% include 'resources/sidebar.html' %}

            <section id="main-content">
                <section class="wrapper">
                    <div class="content">
                        <div class="container">

                            <div class="row">
                                <div class="col-12">
                                    <h3 class="page-header mb-4"><i class="far fa-sticky-note"></i> Reminder</h3>
                                </div>

                                <div class="col-12">
                                    <ol class="breadcrumb bg-light-mode">
                                        <li class="breadcrumb-item"><a href="{% url 'notes:index' %}">Home</a></li>
                                        <li class="breadcrumb-item active" aria-current="page">
                                            <a href="{% url 'reminder:task_list' %}">
                                                <i class="far fa-sticky-note"></i> Reminder
                                            </a>
                                        </li>
                                        <li class="breadcrumb-item active" aria-current="page">
                                            {% if form.instance.id %}
                                                <i class="fas fa-pencil-alt"></i> Edit Task Appointment
                                            {% else %}
                                                <i class="fas fa-plus-square"></i> Set New Task Appointment
                                            {% endif %}
                                        </li>
                                    </ol>
                                </div>
                            </div>

                            <div class="row">
                                <div class="task-form col-12 mt-4">
                                    {% if form.errors %}
                                        <div class="col-md-12 mb-3 text-center text-danger">{{ form.errors }}</div>
                                    {% endif %}
                                    <form class="form-horizontal" id="taskForm" role="form" data-task="{{ task }}"" data-date="{{ date_scheduled }}" data-time="{{ time }}" action="" method="post">
                                        {% csrf_token %}
                                        <div class="form-row">
                                            {% for field in form %}
                                                <div class="form-group col-{{ field.field.widget.attrs.col }}">   
                                                    {{ field.label_tag }}
                                                    {{field}}
                                                    
                                                    <div class="text-danger">
                                                        {{ field.errors }}
                                                    </div>
                                                </div>
                                            {% endfor %}
    

                                            
                                            <div class="form-group col-12">
                                                <div class="float-right">
                                                    <button type="submit" class="btn btn-primary">Save <i class="fas fa-save"></i></button>
                                                    <a href="{% url 'reminder:task_list' %}" class="btn btn-outline-primary">Cancel <i class="fas fa-window-close"></i></a>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>

                        </div>
                    </div>
                </section>
            </section>

        </main>
{% endblock %}

src/studybudy/templates/reminder/Light-mode/taskList.html
{% extends "base/reminder_base.html" %}
{% load static %}
{%  block content %}

        <main>
            {% include 'resources/sidebar.html' %}

            <section id="main-content">
                <section class="wrapper">
                    <div class="content">
                        <div class="container">

                            <div class="row">
                                <div class="col-12">
                                    <h3 class="page-header mb-4"><i class="far fa-sticky-note"></i> Reminder</h3>
                                </div>

                                <div class="col-12">
                                    <ol class="breadcrumb bg-light-mode">
                                        <li class="breadcrumb-item"><a href="{% url 'notes:index' %}">Home</a></li>
                                        <li class="breadcrumb-item active" aria-current="page">
                                            <i class="far fa-sticky-note"></i> Reminder
                                        </li>
                                    </ol>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                    <div class="add-doctor-btn float-left mt-5">
                                        <a href="{% url 'reminder:add_task' %}" class="btn btn-outline-primary">
                                            + Add a New Task
                                        </a>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                            {% if task_list %}
                                <div class="col-12">
                                    <div class="table-responsive bg-light-mode table-list mt-5">
                                        <table class="table table-hover">
                                            <thead>
                                                <tr>
                                                    <th scope="col">S/N</th>
                                                    <th scope="col">Task</th>
                                                    <th scope="col">Date Created</th>
                                                    <th scope="col">Scheduled Time</th>
                                                    <th scope="col">Completed</th>
                                                    <th scope="col">actions</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for tl in task_list %}
                                                    <tr>
                                                        <th scope="row">{{ forloop.counter }}</th>
                                                        <td>
                                                            {{ tl.task }}
                                                            
                                                        </td>
                                                        <td>
                                                            {{ tl.created }}
                                                            
                                                        </td>
                                                        <td>
                                                            {{ tl.time }}
                                                            
                                                        </td>
                                                        {% if tl.completed %}
                                                        <td>
                                                            <div class="custom-control custom-checkbox">
                                                                <input type="checkbox" class="custom-control-input" data-id="{{tl.id}}" data-url="{% url 'reminder:complete_task' %}" id="completecheck-{{tl.id}}" checked="checked" value="False">
                                                                <label class="custom-control-label" for="completecheck-{{tl.id}}">Completed</label>
                                                            </div>
                                                        </td>
                                                        {% else %}
                                                        <td>
                                                            <div class="custom-control custom-checkbox">
                                                                <input type="checkbox" class="custom-control-input" data-id="{{tl.id}}" data-url="{% url 'reminder:complete_task' %}" id="completecheck-{{tl.id}}" value="True">
                                                                <label class="custom-control-label" for="completecheck-{{tl.id}}">Not completed</label>
                                                            </div>
                                                        </td>
                                                        {% endif %}
                                                        <td>
                                                            <div class="drop">
                                                                <a id="fd-{{tl.id}}" class="drop-trigger-options">
                                                                    <i class="fas fa-ellipsis-h"></i>
                                                                </a>
                                                                <div class="drop-meny opy-{{ tl.id}} deactivated">
                                                                    <li id="{{ tl.id }}" data-url="{% url 'reminder:edit_task' tl.id %}" class="edit_task">
                                                                        <a href="#">
                                                                            <i class="fas fa-pencil-alt"></i> Edit Task
                                                                        </a>
                                                                    </li>
                                                                    <li data-id="{{ tl.id }}" data-url="{% url 'reminder:delete_task' %}" data-name="{{ tl.task }}" class="delet_task">
                                                                        <a href="#">
                                                                            <i class="far fa-trash-alt"></i> Delete Task
                                                                        </a>
                                                                    </li>
                                                                    
                                                                </div>
                                                            </div>
                                                        </td>

                                                    </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            {%else %}
                                <div class="col-12 my-5">
                                    <h3 class="text-center text-danger">No Tasks Have Been set Yet</h3>
                                </div>
                            {% endif %}
                            </div>

                        </div>
                    </div>
                </section>
            </section>
            <section id="modal-section">
                <div class="modal fade" id="warningModal" tabindex="-1" role="dialog" aria-labelledby="warningeModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title tile" id="warningModalLabel">Delete</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <div class="container-fluif">
                                    <div class="row">
                                        <div class="col-12 text-center text-danger content-warning">
                                            Are you sure you want to delete
                                        </div>
                                    </div>
                                </div>
                            </div>
                       
                            <div class="modal-footer">
                                <div class="container-fluid">
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="float-right">
                                                <button type="button" data-url="" data-id="" class="yep btn btn-outline-primary" data-dismiss="modal">
                                                    <i class="fas fa-check"></i> Yes
                                                </button>
                                            </div>
                                            <div class="float-left">
                                                <button type="button" class="nope btn btn-outline-danger" data-dismiss="modal">
                                                    <i class="fas fa-times"></i> No
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            
                        </div>
                        </div>
                    </div>
                </div>
            </section>

        </main>
{% endblock %}