src/studybudy/notes/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from . import views

app_name = 'notes'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^upload_notes/$', views.upload_notes, name='upload_notes'),
    url(r'^new_folder/$', views.create_newFolder, name='create_new_folder'),
    url(r'^new_file/$', views.create_newFile, name='create_new_file'),
    url(r'^rename_file/$', views.rename_File, name='rename_file'),
    url(r'^details/$', views.get_details, name='details'),
    url(r'^change_description/$', views.change_description, name='change_description'),
    url(r'^make_public/$', views.make_public, name='ajax_change_public'),
    url(r'^star_file/$', views.star_file, name='star_file'),
    url(r'^share_file/$', views.share_file, name='ajax_share_file'),
    url(r'^open_file/$', views.open_file, name='open_file'),
    url(r'^(?P<file_id>[0-9]+)/open_File/$', views.open_File, name='open_file_new_tab'),
    url(r'^save_file/$', views.save_file, name='save_file'),
    url(r'^delete_file/$', views.delete_file, name='delete_file'),
    url(r'^quiz_note/$', views.quiz_note, name='quiz_note'),
    url(r'^summarize/$', views.summarize, name='summarize'),
    url(r'^quiz_result/$', views.quiz_result, name='quiz_result'),
    url(r'^move_list/$', views.move_list, name='move_list'),
    url(r'^move/$', views.move, name='move'),
    url(r'^(?P<file_id>[0-9]+)/download_file/$', views.download_file, name='download_file'),
    url(r'^filter_note/$', views.filter_note, name='filter_note'),
    url(r'^(?P<order_id>[a-z]+)/order_note/$', views.order_note, name='order_note'),
    # re_path(r'^order_note/(?P<order>[a-z]{4})/(?P<file_type>[a-z]{2})/$', views.order_note, name='order_note'),
    url(r'^(?P<view_id>[a-z]+)/change_view/$', views.change_view, name='change_view'),
    url(r'^stared_note/$', views.stared, name='stared_note'),
    url(r'^shared_note/$', views.shared, name='shared_note'),
    url(r'^(?P<folder_id>[0-9]+)/folder_content/$', views.folder_content, name='folder_content'),
]

src/studybudy/quiz/urls.py
from django.conf.urls import url
from . import views

app_name = 'quiz'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^save_quiz/$', views.save_quiz, name='save_quiz'),
    url(r'^(?P<file_id>[0-9]+)/quiz_attempt/$', views.quiz_attempt, name='quiz_attempt'),
]

src/studybudy/studybudy/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from .views import login_page, register_page, login_user, register_user, logout_user
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
 
 


app_name = 'studybudy'





urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', login_page, name='login_page'),
    url(r'^login_user/$', login_user, name='login_user'),
    url(r'^Register/$', register_page, name='register_page'),
    url(r'^register_user/$', register_user, name='register_user'),
    url(r'^logout/$', logout_user, name='logout_user'),
    url(r'^Dashboard/', include('notes.urls')),
    url(r'^Trash/', include('trash.urls')),
    url(r'^Quiz/', include('quiz.urls')),
    url(r'^User/', include('users.urls')), 
    url(r'^Reminder/', include('reminder.urls'))  
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/studybudy/users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'

urlpatterns = [
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^change/$', views.change, name='change'),
    url(r'^(?P<user_id>[0-9]+)/edit_profile/$', views.edit_profile, name='edit_profile'),
    url(r'^(?P<user_id>[0-9]+)/delete_image/$', views.delete_image, name='delete_image'),
    
]

src/studybudy/users/models.py
import random, os
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import AbstractBaseUser
from .managers import UserManager
from studybudy.settings import BASE_DIR

def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext

def upload_photo_path(instance, filename):
    new_filename = random.randint(1,3910209312)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
    return "profile-photos/{final_filename}".format(final_filename=final_filename)



# Create your models here.
class User(AbstractBaseUser):
    TYPE_CHOICES = [
        ('Admin IT', 'Admin IT'),
        ('Admin Editor', 'Admin Editor'),
        ('Student', 'Student'), 
        ('Teacher', 'Teacher'),
        
    ]

    user_id                     = models.CharField(max_length=50, unique=True, default="")
    first_name                  = models.CharField(max_length=300)
    last_name                   = models.CharField(max_length=300)
    dob                         = models.DateField(null=True)
    age                         = models.IntegerField(default=0)
    sex                         = models.CharField(max_length=10)
    country                     = models.CharField(max_length=50, blank=True)
    state                       = models.CharField(max_length=50, blank=True)
    los                         = models.CharField(max_length=50, blank=True)
    los_class                   = models.CharField(max_length=50, blank=True)
    school                      = models.CharField(max_length=200, blank=True)
    email                       = models.EmailField(max_length=255, unique=True)
    username                    = models.CharField(max_length=255, unique=True)
    telephone                   = models.CharField(max_length=50, default=0, blank=True)
    facebook                    = models.CharField(max_length=50, blank=True)
    twitter                     = models.CharField(max_length=50, blank=True)
    instagram                   = models.CharField(max_length=50, blank=True)
    user_type                   = models.CharField(max_length=50, choices=TYPE_CHOICES,)
    shared_with_me              = models.CharField(max_length=50, blank=True, null=True,)
    profile_photo               = models.ImageField(upload_to=upload_photo_path, null=True, blank=True)
    active                      = models.BooleanField(default=True)# can login
    admin                       = models.BooleanField(default=False)# staff user non superuser
    staff                       = models.BooleanField(default=False)# supersuser
    date_created                = models.DateTimeField(auto_now_add=True)
    last_editted                = models.DateTimeField(blank=True, null=True)
    last_login                  = models.DateTimeField(blank=True, null=True)


    objects = UserManager()

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = ['first_name', 'last_name', 'dob','sex', 'user_type']


    #User Class Properties
    def __str__(self):
        return self.email


    def get_full_name(self):
        '''
        Returns the first_name plus the last_name, with a space in between.
        '''
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        '''
        Returns the short name for the user.
        '''
        short_name = full_name = '%s' % (self.first_name)
        return short_name.strip()

    def get_country_state(self):
        '''
        Returns the country and state for the user.
        '''
        country_state = '%s %s' % (self.country, self.state)
        return country_state.strip()


    def email_user(self, subject, message, from_email=None, **kwargs):
        '''
        Sends an email to this User.
        '''
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True


    @property
    def is_staff(self):
        "Is the user a member of staff?"
        return self.staff

    @property
    def is_admin(self):
        "Is the user a admin member?"
        return self.admin

    @property
    def is_active(self):
        "Is the user active?"
        return self.active



class UserState(models.Model):
    user                = models.OneToOneField(User, on_delete=models.CASCADE, blank=False, null=False, unique=True)
    mode                = models.CharField(max_length=100, default="light")
    folder_order        = models.CharField(max_length=100, default="ASC")
    file_order          = models.CharField(max_length=100, default="ASC")
    file_filters        = models.CharField(max_length=100, default="Name")
    folder_filters      = models.CharField(max_length=100, default="Name")
    view                = models.CharField(max_length=100, default="grid")
    total_storage       = models.BigIntegerField(default=0)

    def user_name(self):
        return self.user.get_full_name()

    def __str__(self):
        return self.user.email


class Notifications(models.Model):
    usey                = models.ForeignKey(User, related_name="notifications_user", on_delete=models.CASCADE, blank=True, null=True,)
    task_id             = models.BigIntegerField(default=0)
    notify              = models.CharField(max_length=200,)
    seen                = models.BooleanField(default=False)

    def __str__(self):
        return self.usey.email

src/studybudy/users/views.py
import os, json, datetime
from datetime import datetime
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from django.contrib.auth import get_user_model
from notes.utils.determine_state import DetermineState
from django.http import HttpResponse, Http404, JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import update_session_auth_hash
from .forms import ProfileForm
from users.models import UserState
from notes.models import FileSystem
from quiz.models import QuizFileSystem
from studybudy.settings import BASE_DIR


media_root = settings.MEDIA_ROOT
Users = get_user_model()

# Create your views here.
@login_required(login_url='/login')
def profile(request):
    sname = None
    if (request.user.is_authenticated):
        sname           = request.user.get_short_name()
        full_name       = request.user.get_full_name()
        profile_pic     = request.user.profile_photo
        dob             = request.user.dob
        utype            = request.user.user_type
        cs              = request.user.get_country_state()
        school          = request.user.school
        email           = request.user.email
        telephone       = request.user.telephone 
        state           = UserState.objects.filter(user=request.user).first()
        DS              = DetermineState(state)
        mode            = DS.determine_mode()
        file_count      = FileSystem.objects.filter(owner=request.user, file_type="file", active=True).count()
        folder_count    = FileSystem.objects.filter(owner=request.user, file_type="folder", active=True).count()
        quiz_count      = QuizFileSystem.objects.filter(owner=request.user, file_type="quiz_file", active=True).count()
        trash_count     = FileSystem.objects.filter(owner=request.user, file_type="file", active=False).count()
        path            = "user/" + mode + "/profile.html"

        context = {
            'short_name'    : sname,
            'full_name'     : full_name,
            'profile_pic'   : profile_pic,
            'dob'           : dob,
            'role'          : utype,
            'cs'            : cs,
            'school'        : school,
            'email'         : email,
            'telephone'     : telephone,
            'file_count'    : file_count,
            'folder_count'  : folder_count,
            'quiz_count'    : quiz_count,
            'trash_count'   : trash_count,
            'user'          : request.user
        }
    else:
        return redirect("/login")

    return render(request, path, context)


@login_required(login_url='/login')
def change_password(request):
    if (request.user.is_authenticated):
        return render(request, "auth/change_password.html")
    else:
        return redirect("/login")


@login_required(login_url='/login')
def edit_profile(request, user_id):
    sname = None
    if (request.user.is_authenticated):
        sname           = request.user.get_short_name()
        state           = UserState.objects.filter(user=request.user).first()
        DS              = DetermineState(state)
        mode            = DS.determine_mode()
        user_inst       = get_object_or_404(Users, pk=user_id)
        orig_pass       = user_inst.password
        form            = ProfileForm(instance=user_inst)
        path            = "user/" + mode + "/editProfile.html"
        # user_i       = get_object_or_404(Users, pk=3)
        # user_i.set_password("password4")
        # user_i.save()


        if request.method == "POST" : 
            form = ProfileForm(request.POST, request.FILES, instance=user_inst)
            # print(form.cleaned_data.get("country"))
            if form.is_valid():
                user = form.save()
                if form.cleaned_data.get("password") == "":
                    user.password = orig_pass
                else:
                    user.set_password(form.cleaned_data.get("password"))
                user.last_editted = datetime.now()
                user.save()

                return redirect('/User/profile/')

        context = {
            'short_name'    : sname,
            'user'          : request.user,
            'form'          : form
        }
    else:
        return redirect("/login")

    return render(request, path, context)


@login_required(login_url='/login')
def delete_image(request, user_id):
    sname = None
    if (request.user.is_authenticated):
        user_inst       = get_object_or_404(Users, pk=user_id)
        user_inst.profile_photo.delete(save=True)
        path            = "/User/" + user_id + "/edit_profile/"
        

    else:
        return redirect("/login")

    return redirect(path)



@login_required(login_url='/login')
def change(request):
    old = request.GET.get('old')
    new = request.GET.get('new')
    data = {}

    if (request.user.is_authenticated):
        user        = get_object_or_404(Users, pk=request.user.id)
        user_old    = user.password

        if old == "" or new =="":
            data['error'] = "Invalid Password entered must be a charcter"
        elif len(new) <= 6:
            data['error'] = "Invalid New Password is not long enough"
        else:
            user.set_password(new)
            user.save()
            update_session_auth_hash(request, user) 
            data["url"] = "/Dashboard"
        

    else:
        return redirect("/login")


           
    return JsonResponse(data)

src/studybudy/templates/user/Light-mode/editProfile.html
{% extends "base/profile_base.html" %}
{% load static %}
{%  block content %}

        <main>
            {% include 'resources/sidebar.html' %}

            <section id="main-content">
                <section class="wrapper">
                    <div class="content">
                        <div class="container">

                            <div class="row">
                                <div class="col-12">
                                    
                                        <h3 class="page-header mb-4"><i class="fas fa-user"></i> Profile</h3>
                                </div>

                                <div class="col-12">
                                    <ol class="breadcrumb bg-light-mode">
                                        <li class="breadcrumb-item"><a href="{% url 'notes:index' %}">Home</a></li>d
                                        <li class="breadcrumb-item active" aria-current="page">
                                            <a href="{% url 'users:profile' %}">
                                                <i class="fas fa-user"></i> {{ short_name }} Profile
                                            </a>
                                        </li>
                                        <li class="breadcrumb-item active" aria-current="page">
                                            <i class="fas fa-pencil-alt"></i> Edit {{ short_name }} Profile
                                        </li>
                                    </ol>
                                </div>
                            </div>

                            <div class="row">
                                <div class="profile-form col-12 mt-4">
                                    {% if form.errors %}
                                        <div class="col-md-12 mb-3 text-center text-danger">{{ form.errors }}</div>
                                    {% endif %}
                                        <form class="form-horizontal" role="form" action="" method="post" id="profileForm" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <div class="form-row">
                                                {% for field in form %}
                                                {% ifequal forloop.counter 7%}
                                                    <div class="form-group col-6">
                                                        <label for="country">Country:</label>
                                                        <select id="country" class="form-control" id="country" placeholder="Select Your Country of Residence" required>
                                                            <option value=""><!---choose-----></option>
                                                        </select>
                                                        <div class="text-danger cty"></div>
                                                    </div>
                                                    
                                                    <div class="form-group col-6">
                                                        <label for="state">State:</label>
                                                        <select id="state" class="form-control" placeholder="Select Your State" required>
                                                            <option value=""><!---choose-----></option>
                                                        </select>
                                                        <div class="text-danger sty"></div>
                                                    </div>
                                                {% else %}
                                                    <div class="form-group col-{{ field.field.widget.attrs.col }}">   
                                                        {{ field.label_tag }}
                                                        {{field}}
                                                        
                                                        <div class="text-danger">
                                                            {{ field.errors }}
                                                        </div>
                                                    </div>
                                                {% endifequal %}
                                                {% endfor %}
                                                {% if user.profile_photo %}
                                                <div class="form-group col-12 profile-image">
                                                    <div class="float-left">
                                                        <img src="{{ user.profile_photo.url }}" style="width: 200px; height: 200pxrem;" alt="profile photo" class="mx-auto img-repsonsive">                                                        
                                                    </div><br>
                                                </div>
                                                <div class="form-group col-12">
                                                    <div class="float-left">
                                                        <a href="{% url 'users:delete_image' user.id %}" class="text-danger">
                                                            .........................<i class="fas fa-window-close"></i> Delete Image
                                                        </a>
                                                    </div>
                                                </div>
                                                {% endif %}
                                                <div class="form-group col-12">
                                                    <div class="float-right">
                                                        <button type="submit" class="btn btn-primary">Save <i class="fas fa-save"></i></button>
                                                        <a href="{% url 'users:profile' %}" class="btn btn-outline-primary">Cancel <i class="fas fa-window-close"></i></a>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                </div>
                            </div>

                        </div>
                    </div>
                </section>
            </section>
        </main>

{% endblock %}

src/studybudy/templates/user/Light-mode/profile.html
{% extends "base/profile_base.html" %}
{% load static %}
{%  block content %}

        <main>
            {% include 'resources/sidebar.html' %}

            <section id="main-content">
                <section class="wrapper">
                    <div class="content">
                        <div class="container">

                            <div class="row">
                                <div class="col-12">
                                    <h3 class="page-header mb-4"><i class="fas fa-user"></i> Profile</h3>
                                </div>

                                <div class="col-12">
                                    <ol class="breadcrumb bg-light-mode">
                                        <li class="breadcrumb-item"><a href="{% url 'notes:index' %}">Home</a></li>
                                        <li class="breadcrumb-item active" aria-current="page">
                                            <i class="fas fa-user"></i> Profile
                                        </li>
                                    </ol>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 my-5">
                                    <div class="card" style="height: 43rem;">
                                        {% if profile_pic %}
                                            <img src="{{ profile_pic.url }}" alt="..." class="mx-auto avatar2"> 
                                        {% else  %}
                                            <img src="{% static "images/profile/avatar.png" %}" alt="..." class="mx-auto avatar2">
                                        {% endif %}
                                        <hr>
                                        <div class="card-body">
                                            <h3 class="card-title display-5">{{ full_name }}</h3>
                                            <h5 class="card-text">
                                                {{ dob }}  
                                            </h5>
                                            <h6 class="card-text">
                                                School : {{ school }}  
                                            </h6>
                                            <h6 class="card-text">
                                                {{ role }}  
                                            </h6>
                                            <h6 class="card-text">
                                                {{ cs }}  
                                            </h6>
                                            <hr>
                                            <h6 class="card-text">
                                                Email : <a href="mailto:{{ email }}" class="card-link">{{ email }}</a>  
                                            </h6>
                                            
                                            <h6 class="card-text">
                                                Telephone : {{ telephone }}  
                                            </h6>
    
                                            <h6 class="card-text mt-3 extend">
                                                <a href="{% url 'users:edit_profile' user.id %}" class="card-link text-mattRed">Edit Profile...</a> 
                                            </h6>
    
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 my-5">
                                    <div class="card" style="height: 20rem;">
                                        <div class="card-body">
                                            <h5 class="card-title mt-2"><i class="far fa-clipboard"></i> Notes</h5>
                                            <h1 class="card-text noa text-center display-1 mt-4">{{ file_count }}</h1>
                                        </div>
                                    </div>
                                    <div class="card bg-dark text-white mt-5" style="height: 20rem;">
                                        <div class="card-body">
                                            <h5 class="card-title mt-2"><i class="far fa-folder"></i> Folders</h5>
                                            <h1 class="card-text noa text-center display-1 mt-4">{{ folder_count }}</h1>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 my-5">
                                    <div class="card" style="height: 20rem;">
                                        <div class="card-body">
                                            <h5 class="card-title mt-2"><i class="fas fa-question"></i> Quiz</h5>
                                            <h1 class="card-text noa text-center display-1 mt-4">{{ quiz_count }}</h1>
                                        </div>
                                    </div>
                                    <div class="card mt-5" style="height: 20rem;">
                                        <div class="card-body">
                                            <h5 class="card-title mt-2"><i class="far fa-trash-alt"></i> Trash</h5>
                                            <h1 class="card-text noa text-center display-1 mt-4">{{ trash_count }}</h1>
                                        </div>
                                    </div>
                                </div>
                            </div>
    
                        </div>
                    </div>
                </section>
            </section>

        </main>
{% endblock %}