src/studybudy/notes/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from . import views

app_name = 'notes'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^upload_notes/$', views.upload_notes, name='upload_notes'),
    url(r'^new_folder/$', views.create_newFolder, name='create_new_folder'),
    url(r'^new_file/$', views.create_newFile, name='create_new_file'),
    url(r'^rename_file/$', views.rename_File, name='rename_file'),
    url(r'^details/$', views.get_details, name='details'),
    url(r'^change_description/$', views.change_description, name='change_description'),
    url(r'^make_public/$', views.make_public, name='ajax_change_public'),
    url(r'^star_file/$', views.star_file, name='star_file'),
    url(r'^share_file/$', views.share_file, name='ajax_share_file'),
    url(r'^open_file/$', views.open_file, name='open_file'),
    url(r'^(?P<file_id>[0-9]+)/open_File/$', views.open_File, name='open_file_new_tab'),
    url(r'^save_file/$', views.save_file, name='save_file'),
    url(r'^delete_file/$', views.delete_file, name='delete_file'),
    url(r'^quiz_note/$', views.quiz_note, name='quiz_note'),
    url(r'^summarize/$', views.summarize, name='summarize'),
    url(r'^quiz_result/$', views.quiz_result, name='quiz_result'),
    url(r'^move_list/$', views.move_list, name='move_list'),
    url(r'^move/$', views.move, name='move'),
    url(r'^(?P<file_id>[0-9]+)/download_file/$', views.download_file, name='download_file'),
    url(r'^filter_note/$', views.filter_note, name='filter_note'),
    url(r'^(?P<order_id>[a-z]+)/order_note/$', views.order_note, name='order_note'),
    # re_path(r'^order_note/(?P<order>[a-z]{4})/(?P<file_type>[a-z]{2})/$', views.order_note, name='order_note'),
    url(r'^(?P<view_id>[a-z]+)/change_view/$', views.change_view, name='change_view'),
    url(r'^stared_note/$', views.stared, name='stared_note'),
    url(r'^shared_note/$', views.shared, name='shared_note'),
    url(r'^(?P<folder_id>[0-9]+)/folder_content/$', views.folder_content, name='folder_content'),
]

src/studybudy/quiz/urls.py
from django.conf.urls import url
from . import views

app_name = 'quiz'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^save_quiz/$', views.save_quiz, name='save_quiz'),
    url(r'^(?P<file_id>[0-9]+)/quiz_attempt/$', views.quiz_attempt, name='quiz_attempt'),
]

src/studybudy/studybudy/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from .views import login_page, register_page, login_user, register_user, logout_user
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
 
 


app_name = 'studybudy'





urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', login_page, name='login_page'),
    url(r'^login_user/$', login_user, name='login_user'),
    url(r'^Register/$', register_page, name='register_page'),
    url(r'^register_user/$', register_user, name='register_user'),
    url(r'^logout/$', logout_user, name='logout_user'),
    url(r'^Dashboard/', include('notes.urls')),
    url(r'^Trash/', include('trash.urls')),
    url(r'^Quiz/', include('quiz.urls')),
    url(r'^User/', include('users.urls')), 
    url(r'^Reminder/', include('reminder.urls'))  
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/studybudy/trash/urls.py
from django.conf.urls import url
from . import views

app_name = 'trash'

urlpatterns = [
    url(r'^$', views.trash, name='trash'),
    url(r'^recycle_list/$', views.recycle_list, name='recycle_list'),
    url(r'^recycle/$', views.recycle, name='recycle'),
    url(r'^delete_permanently', views.delete_permanently, name='delete_permanently'),
    url(r'^details/$', views.get_details, name='details'),

]

src/studybudy/notes/models.py
import random, os
from django.db import models
from users.models import User

# Create your models here.
def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext

def upload_image_path(instance, filename):
    new_filename = random.randint(1,3910209312)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
    return "Notes/{new_filename}/{final_filename}".format(new_filename=new_filename, final_filename=final_filename)


class FileSystem(models.Model):
    name            = models.CharField(max_length=200)
    folder          = models.BigIntegerField(default=0)
    file_type       = models.CharField(max_length=50, blank=True, null=True,)
    size            = models.BigIntegerField(default=0)
    owner           = models.ForeignKey(User, related_name="Owner", on_delete=models.CASCADE, blank=True, null=True,)
    location        = models.FileField(upload_to=upload_image_path, null=True, blank=True)
    starred         = models.BooleanField(default=False)
    public          = models.BooleanField(default=False)
    sharable        = models.BooleanField(default=False)
    shared_with     = models.CharField(max_length=50, blank=True, null=True,)
    words           = models.CharField(max_length=500, blank=True, null=True,)
    time_taken      = models.BigIntegerField(default=0)
    description     = models.TextField(blank=True, null=True,)
    quized          = models.BooleanField(default=False)
    quized_saved    = models.BooleanField(default=False)
    active          = models.BooleanField(default=True)
    date_created    = models.DateTimeField(auto_now_add=True)
    last_editted_by = models.ForeignKey(User, related_name="editted_by", on_delete=models.CASCADE, blank=True, null=True,)
    last_editted    = models.DateTimeField(blank=True, null=True)
    last_opened     = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.name


    def get_owner_full_name(self):
        '''
        Returns the first_name plus the last_name, with a space in between.
        '''
        full_name = '%s %s' % (self.owner.first_name, self.owner.last_name)
        return full_name

    def get_owner_short_name(self):
        '''
        Returns the short name for the user.
        '''
        short_name = full_name = '%s' % (self.owner.first_name)
        return short_name.strip()

src/studybudy/trash/models.py
from django.db import models

# Create your models here.

src/studybudy/notes/views.py
import json, os, re, pytz, random, pdfkit 
import time, mimetypes
from datetime import datetime
from django.utils import timezone
from .utils.converter import Converter
from .utils.determine_state import DetermineState
from .utils.remove_share import RemoveShare
from django.shortcuts import render
from django.db.models import Q
from django.conf import settings
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from wsgiref.util import FileWrapper
from studybudy.settings import BASE_DIR
from .models import FileSystem
from users.models import UserState
from .app import Application


media_root = settings.MEDIA_ROOT
Users = get_user_model()

# Create your views here.
@login_required(login_url='/login')
def index(request):
    
    sname = None
    if (request.user.is_authenticated):
        sname           = request.user.get_short_name()
        state           = UserState.objects.filter(user=request.user).first()
        starred         = FileSystem.objects.filter(starred=1, active=True, owner=request.user.id).count()
        sharred         = len(eval(request.user.shared_with_me))
        DS              = DetermineState(state)

        fryp, fry       = DS.determine_order()
        filt, folt      = DS.determine_tab_filter()
        mode            = DS.determine_mode()
        recent          = FileSystem.objects.filter(active=True, owner=request.user.id, file_type="file").order_by('-last_opened')[:4]
        folders         = FileSystem.objects.filter(active=True, owner=request.user.id, folder= 0, file_type="folder").order_by(fryp)
        all_files       = FileSystem.objects.filter(active=True, owner=request.user.id, folder=0, file_type="file",).order_by(fry)
        path            = "notes/" + mode + "/index.html"
        

        if len(all_files) > 4:
            files = []
            for a_file in all_files:
                if a_file in recent:
                    pass
                else:
                    files.append(a_file)
            all_files = files

        context = {
            'short_name': sname,
            'starred'   : starred,
            'sharred'   : sharred,
            'recent'    : recent,
            'folders'   : folders,
            'files'     : all_files,
            'state'     : state,
            "filt"      : filt,
            "folt"      : folt,
        }
    else:
        return redirect("/login")

    return render(request, path, context)


@login_required(login_url='/login')
@csrf_exempt
def upload_notes(request):
    data = {}
    if (request.user.is_authenticated):
        user_state  = UserState.objects.get(user=request.user)
        file_model  = FileSystem()
        _, file     = request.FILES.popitem()  # get first element of the uploaded files
        fold        = request.POST.get('fold')
        # print(fold)

           
        for f in file:
            file_name = f.name
            name, ext = os.path.splitext(file_name)
            qs        = FileSystem.objects.filter(name=name, owner=request.user, active=True)
            print(qs)
            
            
            if ext == ".pdf":
                if qs is None and  qs.exists() == False:
                    file_model.name             = name.capitalize()
                    file_model.location         = f
                    file_model.file_type        = "file"
                    file_model.owner            = request.user
                    file_model.last_editted_by  = request.user
                    file_model.size             = f.size
                    if fold and fold != "undefined":
                        file_model.folder   = int(fold)
                    file_model.save()
                    prev_size                   = user_state.total_storage
                    user_state.total_storage    = prev_size + f.size
                    user_state.save()
                else:
                    data["error"] = "File Input is invalid, File already exist in Database"
                    return JsonResponse(data)
            else:
                data["error"] = "File Input is invalid, Only PDF files Allowed"
                return JsonResponse(data)

        data['url'] = "/Dashboard"
    else:
        return redirect("/login")
        
    return JsonResponse(data)


@login_required(login_url='/login')
def create_newFolder(request):
    folder_name = request.GET.get('filename')
    description = request.GET.get('description')
    ids         = request.GET.get('id')
    file_model = FileSystem()
    data = {}

    if (request.user.is_authenticated):
        qs = FileSystem.objects.filter(name=folder_name, owner=request.user, active= True)
        fd = FileSystem.objects.filter(active=True, owner=request.user, id=ids, file_type="folder").first()
        fdr = FileSystem.objects.filter(active=True, id=ids, file_type="folder").first()
        picolo = re.match("/^(?:[A-Za-z]+)(?:[A-Za-z0-9 _-]*)$/", str(folder_name))
        ricolo = re.match("/^[A-Za-z0-9.\s_-]*$/", str(description))

        if qs is not None and qs.exists() == True:
            data["error"] = "Folder Input name is invalid"
            return JsonResponse(data)
        elif picolo == False or ricolo == False:
            data["error"] = "Folder Input name  is invalid"
            return JsonResponse(data)
        if ids is not None:
            if fdr.shared_with is None or fdr.shared_with == "":
                fsw = []
            else:
                fsw = eval(fdr.shared_with)
            if fd is None and str(request.user.id) not in fsw:
                data["error"] = "You are not allowed to accees this folder"
                return JsonResponse(data)
            elif str(request.user.id) in fsw and fdr.public == False:
                data["error"] = "You are not allowed to accees this folder"
                return JsonResponse(data)
            elif str(request.user.id) in fsw and fdr.public == True:
                sw                      = []
                sw.append(str(fdr.owner.id))
                if ids is not None:
                    file_model.folder = int(ids)
                file_model.name         = str(folder_name)
                file_model.file_type    = "folder"
                file_model.owner        = request.user
                file_model.shared_with  = sw
                file_model.description  = description
                file_model.save()
            else: 
                file_model.folder = int(ids)
                file_model.name         = str(folder_name)
                file_model.file_type    = "folder"
                file_model.owner        = request.user
                file_model.description  = description
                file_model.save()
        else:
            file_model.name         = str(folder_name)
            file_model.file_type    = "folder"
            file_model.owner        = request.user
            file_model.description  = description
            file_model.save()


        data['url'] = "/Dashboard"
    else:
        return redirect("/login")
        
    return JsonResponse(data)


@login_required(login_url='/login')
def create_newFile(request):

    file_name   = request.GET.get('fileName').capitalize()
    description = request.GET.get('description')
    fileType    = request.GET.get('fileType')
    fold        = request.GET.get('fold')
    file_model  = FileSystem()
    picolo = re.match("/^(?:[A-Za-z]+)(?:[A-Za-z0-9 _-]*)$/", str(file_name))
    ricolo = re.match("/^[A-Za-z0-9.\s_-]*$/", str(description))
    
    data = {}

    if (request.user.is_authenticated):
        qs = FileSystem.objects.filter(name=file_name, owner=request.user, active=True)

        if qs is not None and qs.exists() == True:
            data["error"] = "File Input name is invalid, already exist"
            return JsonResponse(data)
        elif picolo == False or ricolo == False:
            data["error"] = "File Input name  is invalid"
            return JsonResponse(data)
        else:
            file_model.name         = str(file_name)
            file_model.file_type    = fileType
            file_model.owner        = request.user
            file_model.description  = description
            if fold:
                file_model.folder   = int(fold)
            file_model.save()

            data['msg'] = fileType.capitalize() + " created successfully"
        

        data['url'] = "/Dashboard"
    else:
        return redirect("/login")
        
    return JsonResponse(data)


@login_required(login_url="/login")
def rename_File(request):
    file_name   = request.GET.get('fileName').capitalize()
    description = request.GET.get('description')
    fileType    = request.GET.get('fileType')
    ID          = request.GET.get('ID')
    picolo = re.match("/^(?:[A-Za-z]+)(?:[A-Za-z0-9 _-]*)$/", str(file_name))
    ricolo = re.match("/^[A-Za-z0-9.\s_-]*$/", str(description))
    
    data = {}

    if (request.user.is_authenticated):
        file_model  = FileSystem.objects.get(pk=int(ID))
        qs = FileSystem.objects.filter(name=file_name, owner=request.user, active=True)

        if file_model is None:
            data["error"] = "Something went wrong, please try again"
            return JsonResponse(data)
        elif picolo == False or ricolo == False:
            data["error"] = "File Input name  is invalid"
            return JsonResponse(data)
        else:
            file_model.name         = str(file_name)
            file_model.file_type    = fileType
            file_model.owner        = request.user
            file_model.description  = description
            file_model.save()
            data['msg'] = fileType.capitalize() + " Renamed successfully"
        

        data['url'] = "/Dashboard"
    else:

src/studybudy/templates/trash/resources/folders.html
                                                                <div class="my-notes-heading">
                                                                <h2><i class="fas fa-folder"></i><strong>Folders</strong></h2>
                                                                <div class="my-notes-filter">
                                                                    <a href="#">
                                                                        <p class="folder-filter-class">
                                                                            {{ state.folder_filters }}
                                                                        </p>
                                                                    </a>
                                                                    {% ifequal state.folder_order "ASC" %}
                                                                    <a href="{% url 'notes:order_note' 'folder' %}"  class="order-folder">
                                                                        <p class="folder-order">
                                                                            <i class="fas fa-arrow-up"></i>
                                                                        </p>
                                                                    </a>
                                                                    {% else %}
                                                                    <a href="{% url 'notes:order_note' 'folder' %}" class="order-folder">
                                                                        <p class="folder-order">
                                                                            <i class="fas fa-arrow-down"></i>
                                                                        </p>
                                                                    </a> 
                                                                    {% endifequal %}   
                                                                </div>
                                                                <ul class="filter-options-menu deactivated  option-folder-filter">
                                                                <li class="filters-folder" data-url="{% url 'notes:filter_note' %}" data-hml="Name">
                                                                    <i class=""></i><a href="#" class="folder-filt-1"> Name</a>
                                                                </li>
                                                                <li class="filters-folder" data-url="{% url 'notes:filter_note' %}" data-hml="Last Modified">
                                                                    <i class=""></i><a href="#" class="folder-filt-2"> Last Modified</a>
                                                                </li>
                                                                <li class="filters-folder" data-url="{% url 'notes:filter_note' %}" data-hml="Last Opened">
                                                                    <i class=""></i><a href="#" class="folder-filt-3"> Last Opened</a>
                                                                </li>
                                                                </ul>
                                                                </div>
                                                                <hr>

                                                                <div class="my-notes-body">
                                                                    <div class="container-fluid">
                                                                        {% if folders %}

                                                                        <div class="row">
                                                                            {% for fld in folders %}
                                                                            <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                                                                                <div class="folder my-5">
                                                                                    <a href="#">
                                                                                        <h5 data-toggle="tooltip" data-placement="bottom" title="{{fld.name}}">
                                                                                            <i class="fas fa-folder"></i> {{fld.name}}
                                                                                        </h5>
                                                                                        
                                                                                        <div class="folds-options">
                                                                                            <a href="#">
                                                                                                <div id="fd-{{fld.id}}" class="options-icon-fd"></div>
                                                                                            </a>
                                                                                        </div>
                                                                                    </a>
                                                                            
                                                                                    <ul class="folder-options-menu fd-op-{{ fld.id}} deactivated">
                                                                                        <li id="details-{{ fld.id }}" data-id="{{fld.id }}" data-name="{{ fld.name }}" data-type="{{ fld.file_type }}" class="details" data-url="{% url 'trash:details' %}">
                                                                                            <a href="#">
                                                                                                <i class="fas fa-info-circle"></i> Details
                                                                                            </a>
                                                                                        </li>
                                                                                        <li id="recycle-{{ fld.id }}" data-id="{{fld.id }}" data-name="{{ fld.name }}" data-type="{{ fld.file_type }}" class="recycle" data-url="{% url 'trash:recycle_list' %}">
                                                                                            <a href="#">
                                                                                                <i class="fas fa-trash-restore"></i> Restore
                                                                                            </a>
                                                                                        </li>
                                                                                        <li data-id="{{ fld.id }}" data-filename="{{ fld.name }}" data-type="{{ fld.file_type }}" data-url="{% url 'trash:delete_permanently' %}" class="delete-trigger">
                                                                                            <a href="#" class="">
                                                                                                <i class="far fa-trash-alt"></i> Delete Permanently
                                                                                            </a>
                                                                                        </li>
                                                                                    </ul>
                                                                                </div>
                                                                            </div>
                                                                            {% endfor %}
                                                                        </div>

                                                                        {% else %}
                                                                        <div class="row">
                                                                            <div class="col-12 my-5">
                                                                                <h6 class="text-center text-danger">NO FOLDERS AVAILABLE</h6>
                                                                            </div>
                                                                        </div>
                                                                        {% endif %}
                                                                    </div>
                                                                </div>