src/studybudy/notes/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from . import views

app_name = 'notes'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^upload_notes/$', views.upload_notes, name='upload_notes'),
    url(r'^new_folder/$', views.create_newFolder, name='create_new_folder'),
    url(r'^new_file/$', views.create_newFile, name='create_new_file'),
    url(r'^rename_file/$', views.rename_File, name='rename_file'),
    url(r'^details/$', views.get_details, name='details'),
    url(r'^change_description/$', views.change_description, name='change_description'),
    url(r'^make_public/$', views.make_public, name='ajax_change_public'),
    url(r'^star_file/$', views.star_file, name='star_file'),
    url(r'^share_file/$', views.share_file, name='ajax_share_file'),
    url(r'^open_file/$', views.open_file, name='open_file'),
    url(r'^(?P<file_id>[0-9]+)/open_File/$', views.open_File, name='open_file_new_tab'),
    url(r'^save_file/$', views.save_file, name='save_file'),
    url(r'^delete_file/$', views.delete_file, name='delete_file'),
    url(r'^quiz_note/$', views.quiz_note, name='quiz_note'),
    url(r'^summarize/$', views.summarize, name='summarize'),
    url(r'^quiz_result/$', views.quiz_result, name='quiz_result'),
    url(r'^move_list/$', views.move_list, name='move_list'),
    url(r'^move/$', views.move, name='move'),
    url(r'^(?P<file_id>[0-9]+)/download_file/$', views.download_file, name='download_file'),
    url(r'^filter_note/$', views.filter_note, name='filter_note'),
    url(r'^(?P<order_id>[a-z]+)/order_note/$', views.order_note, name='order_note'),
    # re_path(r'^order_note/(?P<order>[a-z]{4})/(?P<file_type>[a-z]{2})/$', views.order_note, name='order_note'),
    url(r'^(?P<view_id>[a-z]+)/change_view/$', views.change_view, name='change_view'),
    url(r'^stared_note/$', views.stared, name='stared_note'),
    url(r'^shared_note/$', views.shared, name='shared_note'),
    url(r'^(?P<folder_id>[0-9]+)/folder_content/$', views.folder_content, name='folder_content'),
]

src/studybudy/quiz/urls.py
from django.conf.urls import url
from . import views

app_name = 'quiz'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^save_quiz/$', views.save_quiz, name='save_quiz'),
    url(r'^(?P<file_id>[0-9]+)/quiz_attempt/$', views.quiz_attempt, name='quiz_attempt'),
]

src/studybudy/reminder/urls.py
from django.conf.urls import url
from . import views

app_name = 'reminder'

urlpatterns = [
    url(r'^$', views.task_list, name='task_list'),
    url(r'^add_task/$', views.add_task, name='add_task'),
    url(r'^(?P<task_id>[0-9]+)/edit_task/$', views.edit_task, name='edit_task'),
    url(r'^delete_task/$', views.delete_task, name='delete_task'),
    url(r'^complete_task/$', views.complete_task, name='complete_task'),
    # url(r'^add_task/$', AppointmentCreateView.as_view(), name='add_task'),

]

src/studybudy/studybudy/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from .views import login_page, register_page, login_user, register_user, logout_user
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
 
 


app_name = 'studybudy'





urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', login_page, name='login_page'),
    url(r'^login_user/$', login_user, name='login_user'),
    url(r'^Register/$', register_page, name='register_page'),
    url(r'^register_user/$', register_user, name='register_user'),
    url(r'^logout/$', logout_user, name='logout_user'),
    url(r'^Dashboard/', include('notes.urls')),
    url(r'^Trash/', include('trash.urls')),
    url(r'^Quiz/', include('quiz.urls')),
    url(r'^User/', include('users.urls')), 
    url(r'^Reminder/', include('reminder.urls'))  
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/studybudy/trash/urls.py
from django.conf.urls import url
from . import views

app_name = 'trash'

urlpatterns = [
    url(r'^$', views.trash, name='trash'),
    url(r'^recycle_list/$', views.recycle_list, name='recycle_list'),
    url(r'^recycle/$', views.recycle, name='recycle'),
    url(r'^delete_permanently', views.delete_permanently, name='delete_permanently'),
    url(r'^details/$', views.get_details, name='details'),

]

src/studybudy/users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'

urlpatterns = [
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^change/$', views.change, name='change'),
    url(r'^(?P<user_id>[0-9]+)/edit_profile/$', views.edit_profile, name='edit_profile'),
    url(r'^(?P<user_id>[0-9]+)/delete_image/$', views.delete_image, name='delete_image'),
    
]

src/studybudy/templates/resources/navbar.html
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-light-mode border-bottom fixed-top">
                <div class="toggle-nav">
                    <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom">
                        <i class="fas fa-bars"></i>
                    </div>
                </div>

                <a href="{% url 'notes:index' %}" class="logo">
                    STUDY <span class="lite">BUDY</span>
                </a>

                <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <!-- <span class="navbar-toggler-icon"></span> -->
                    <i class="fas fa-bars"></i>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                        <!-- <li class="nav-item dropdown dropdown-place">
                            <a class="nav-link dropdown-toggle not-caret" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="far fa-bell"></i>
                                <span class="info-count"> 6 </span>
                            </a>
                            <div class="dropdown-menu notifications-menu" aria-labelledby="navbarDropdown">
                                <p class="blue">You have 6 pending letter</p>
                                <a class="dropdown-item" href="#">
                                    <div class="task-info">
                                        <div class="desc"> Project 1</div>
                                        <div class="percent">30%</div>
                                    </div>
                                    <div class="progress progress-striped">
                                        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100" style="width: 30%">
                                        <span class="sr-only">30% Complete (warning)</span>
                                        </div>
                                    </div>
                                </a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">
                                    <div class="task-info">
                                        <div class="desc">Design PSD </div>
                                        <div class="percent">90%</div>
                                    </div>
                                    <div class="progress progress-striped">
                                        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width: 90%">
                                        <span class="sr-only">90% Complete (success)</span>
                                        </div>
                                    </div>
                                </a>
                                <a href="#">See All Tasks</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown dropdown-place">
                            <a class="nav-link dropdown-toggle not-caret" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="far fa-comments"></i>
                                <span class="info-count"> 5 </span>
                            </a>
                            <div class="dropdown-menu message-menu" aria-labelledby="navbarDropdown">
                                <p class="blue">You have 6 pending letter</p>
                                {% load static %}
                                <a href="#">
                                    <span class="photo"><img alt="avatar" src="{% static "images/profile-photo/avatar-mini.jpg" %}"></span>
                                    <span class="subject">
                                    <span class="from">Greg  Martin</span>
                                    <span class="time">1 min</span>
                                    </span>
                                    <span class="message">
                                        I really like this admin panel.
                                    </span>
                                </a>
                                <a href="#">
                                    <span class="photo"><img alt="avatar" src="{% static "images/profile-photo/avatar-mini2.jpg" %}"></span>
                                    <span class="subject">
                                    <span class="from">Bob   Mckenzie</span>
                                    <span class="time">5 mins</span>
                                    </span>
                                    <span class="message">
                                    Hi, What is next project plan?
                                    </span>
                                </a>
                                <a href="#">
                                    <span class="photo"><img alt="avatar" src="{% static "images/profile-photo/avatar-mini3.jpg" %}"></span>
                                    <span class="subject">
                                    <span class="from">Phillip   Park</span>
                                    <span class="time">2 hrs</span>
                                    </span>
                                    <span class="message">
                                        I am like to buy this Admin Template of the outsid epart of the oga.
                                    </span>
                                </a>
                                <a href="#">
                                    <span class="photo"><img alt="avatar" src="{% static "images/profile-photo/avatar1_small.jpg" %}"></span>
                                    <span class="subject">
                                    <span class="from">Ray   Munoz</span>
                                    <span class="time">1 day</span>
                                    </span>
                                    <span class="message">
                                        Icon fonts are great.
                                    </span>
                                </a>
                                <a href="#">See all messages</a>
                                
                            </div>
                        </li> -->
                        <li class="nav-item dropdown dropdown-place caret">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Welcome {{ short_name }}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'users:profile' %}"><i class="fas fa-user"></i> Profile</a>
                                <a class="dropdown-item" href="{% url 'users:change_password' %}"> <i class="fas fa-key"></i> Change Password</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="/logout"><i class="fas fa-sign-out-alt"></i> Log-Out</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

src/studybudy/templates/resources/sidebar.html
            <div id="sidebar" class="nav-collapse">
                <ul class="sidebar-menu">
                    <li class="">
                        <a class="" href="{% url 'notes:index' %}">
                            <i class="far fa-clipboard"></i>
                            <span>My Notes</span>
                        </a>
                    </li>
                    <!-- <li>
                        <a class="" href="">
                            <i class="fas fa-question"></i>
                            <span>Quiz</span>
                        </a>
                    </li> -->
                    <li>
                        <a class="" href="{% url 'reminder:task_list' %}">
                            <i class="far fa-sticky-note"></i>
                            <span>Reminder</span>
                        </a>
                    </li>
                    <li>
                        <a class="" href="{% url 'trash:trash' %}">
                            <i class="far fa-trash-alt"></i>
                            <span>Trash</span>
                        </a>
                    </li>
                    <!-- <li>
                        <a class="" href="index.html">
                            <i class="fas fa-cog"></i>
                            <span>Settings</span>
                        </a>
                    </li> -->
                    <li>
                        <a class="sideMenuToggler" href="#">
                            <i class="fas fa-angle-double-left"></i>
                            <span>Minimize</span>
                        </a>
                    </li>
                </ul>
            </div>